name: firehack
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=gpu_0
  - affine=2.4.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h3485c13_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.8.0=h2219d47_15
  - aws-c-cal=0.8.1=h099ea23_3
  - aws-c-common=0.10.6=h2466b09_0
  - aws-c-compression=0.3.0=h099ea23_5
  - aws-c-event-stream=0.5.0=h85d8506_11
  - aws-c-http=0.9.2=h3888f84_4
  - aws-c-io=0.15.3=hc5a9e45_6
  - aws-c-mqtt=0.11.0=h2c94728_12
  - aws-c-s3=0.7.7=h6a38c86_0
  - aws-c-sdkutils=0.2.1=h099ea23_4
  - aws-checksums=0.2.2=h099ea23_4
  - aws-crt-cpp=0.29.7=h0642867_7
  - aws-sdk-cpp=1.11.458=h5f5f9c4_4
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.1.0=py311h71c1bcc_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=h85f69ea_0
  - bokeh=3.8.0=pyhd8ed1ab_0
  - boost-cpp=1.82.0=h6f18f0d_6
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py311h3e6a449_4
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.12.2=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h91e5215_2
  - cartopy=0.25.0=py311h11fd7f3_1
  - cdsapi=0.7.7=pyhd8ed1ab_0
  - certifi=2026.01.04=py311haa95532_0
  - cffi=2.0.0=py311h3485c13_1
  - cfitsio=3.470=h0af3d06_7
  - cftime=1.6.4=py311h17033d2_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.1.8=pyh7428d3b_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py311h3485c13_1
  - dash=2.7.0=pyhd8ed1ab_0
  - dask=2025.10.0=pyhcf101f3_0
  - dask-core=2025.10.0=pyhcf101f3_0
  - dav1d=1.2.1=hcfcfb64_0
  - dbfread=2.0.7=py_0
  - debugpy=1.8.17=py311h5dfdfe8_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2025.10.0=pyhcf101f3_0
  - ecmwf-datastores-client=0.4.0=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hac47afa_0
  - fiona=1.10.1=py311h5da7b33_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-compress=1.23=pyhcf101f3_0
  - flask_cors=3.0.10=pyhd3deb0d_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311h3f79411_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=h8276f4a_0
  - fribidi=1.0.16=hfd05255_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gdal=3.6.2=py311hc82fbf4_9
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.10.6=hd4c2148_0
  - geotiff=1.7.0=h4545760_3
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.12.1=h51c971a_3
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kealib=1.5.0=hde4a422_1
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libaec=1.1.4=h20038f6_0
  - libarchive=3.7.7=h88ece9c_0
  - libarrow=18.1.0=hfb2d516_4_cpu
  - libarrow-acero=18.1.0=hb6457b2_4_cpu
  - libarrow-dataset=18.1.0=hb6457b2_4_cpu
  - libarrow-substrait=18.1.0=h30d554c_4_cpu
  - libavif=1.3.0=he916da2_2
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=35_h5709861_mkl
  - libboost=1.82.0=h65993cd_6
  - libboost-devel=1.82.0=h91493d7_6
  - libboost-headers=1.82.0=h57928b3_6
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=14.0.6=default_h77d9078_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.16.0=h43ecb02_0
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgdal=3.6.2=he0cae08_9
  - libglib=2.84.2=h405b238_0
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.31.0=h07d40e7_0
  - libgoogle-cloud-storage=2.31.0=he5eb982_0
  - libgrpc=1.67.1=h7aa3b8a_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkml=1.3.0=h68a222c_1022
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libnetcdf=4.8.1=h6685c40_4
  - libparquet=18.1.0=he61daf8_4_cpu
  - libpng=1.6.50=h7351971_1
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.28.2=hcaed137_0
  - libre2-11=2024.07.02=h4eb7d71_2
  - libsodium=1.0.20=hc70643c_0
  - libspatialite=5.1.0=h6715bb4_2
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.5.1=h44ae7cf_1
  - libutf8proc=2.9.0=h2466b09_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxgboost=3.0.1=cpu_h0649c51_2
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.3=hfa2b4ca_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py311h8b5e962_1
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.7=py311h1ea47a8_0
  - matplotlib-base=3.10.7=py311h1675fdf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - metpy=1.7.1=pyhd8ed1ab_0
  - minizip=4.0.6=hb638d1e_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2024.2.2=h57928b3_16
  - msgpack-python=1.1.2=py311h3fd045d_1
  - multiurl=0.3.7=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - narwhals=2.9.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=py311hd3e7ead_1
  - networkx=3.5=pyhe01879c_0
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openjpeg=2.5.2=hae555c5_0
  - openpyxl=3.1.5=py311h4d8bf61_2
  - openssl=3.5.4=h725018a_0
  - orc=2.0.3=h34659fe_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=h17e33f8_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h096bfcc_0
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - poppler=24.09.0=h6558a74_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - proj=9.3.1=ha107b6e_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.1=py311h3485c13_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.1=cpu_pyheee7c3a_2
  - pyarrow=18.1.0=py311h1ea47a8_0
  - pyarrow-core=18.1.0=py311hdea38fa_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.10.0=py311he5c4563_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.6.1=py311h82130bc_5
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pyside6=6.7.2=py311h2e8c42f_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_1
  - pywinpty=2.0.15=py311hda3d55a_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qhull=2020.2=hc790b64_5
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtshadertools=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebengine=6.7.2=h601c93c_0
  - qtwebsockets=6.7.3=h885b0b7_1
  - rasterio=1.4.3=py311he5c4563_0
  - rasterstats=0.20.0=pyhd8ed1ab_2
  - rav1e=0.7.1=ha073cba_3
  - re2=2024.07.02=haf4117d_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rioxarray=0.18.1=pyhd8ed1ab_0
  - rpds-py=0.27.1=py311hf51aa87_1
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - scipy=1.16.2=py311h9a1c30b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=py311haa95532_0
  - shap=0.47.2=cpu_py311h70bd763_0
  - shapely=2.1.1=py311hbe77627_0
  - simplejson=3.19.2=py311ha68e1ae_0
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h17033d2_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2021.13.0=hd094cb3_4
  - tblib=3.1.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh6dadd2b_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiledb=2.3.3=hd8964de_3
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=hf199647_0
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py311h3485c13_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h8577fbf_1
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py311h3485c13_1
  - unidecode=1.4.0=py311haa95532_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xarray=2025.10.1=py311haa95532_0
  - xerces-c=3.2.5=he0c23c2_2
  - xgboost=3.0.1=cpu_pyhc1a9e11_2
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - adjusttext==1.3.0
      - cattrs==25.3.0
      - flatbuffers==25.9.23
      - hdbscan==0.8.41
      - jh2==5.0.10
      - llvmlite==0.46.0
      - niquests==3.15.2
      - numba==0.63.1
      - numpy==2.3.4
      - openmeteo-requests==1.7.4
      - openmeteo-sdk==1.22.0
      - pynndescent==0.5.13
      - qh3==1.5.5
      - requests-cache==1.2.1
      - retry-requests==2.0.0
      - scikit-posthocs==0.11.4
      - umap-learn==0.5.9.post2
      - url-normalize==2.2.1
      - urllib3-future==2.14.906
      - wassima==2.0.2
prefix: C:\Conda\envs\firehack
