name: geoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - _py-xgboost-mutex=2.0
  - affine=2.4.0
  - anyio=4.11.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - babel=2.17.0
  - backports.zstd=1.1.0
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - boost-cpp=1.82.0
  - branca=0.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cartopy=0.25.0
  - cdsapi=0.7.7
  - certifi=2025.11.12
  - cffi=2.0.0
  - cfitsio=3.470
  - cftime=1.6.4
  - charset-normalizer=3.4.4
  - click=8.1.8
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - cytoolz=1.1.0
  - dash=2.7.0
  - dask=2025.10.0
  - dask-core=2025.10.0
  - dav1d=1.2.1
  - dbfread=2.0.7
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.10.0
  - ecmwf-datastores-client=0.4.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fiona=1.10.1
  - flask=3.1.2
  - flask-compress=1.23
  - flask_cors=3.0.10
  - flexcache=0.3
  - flexparser=0.4
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freeglut=3.4.0
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - fsspec=2025.9.0
  - gdal=3.6.2
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.10.6
  - geotiff=1.7.0
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9e
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kealib=1.5.0
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libarchive=3.7.7
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcurl=8.16.0
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal=3.6.2
  - libglib=2.84.2
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkml=1.3.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libparquet=18.1.0
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.5.1
  - libutf8proc=2.9.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxgboost=3.0.1
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.3
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.1.7
  - metpy=1.7.1
  - minizip=4.0.6
  - mistune=3.1.4
  - mkl=2024.2.2
  - msgpack-python=1.1.2
  - multiurl=0.3.7
  - munkres=1.1.4
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - narwhals=2.9.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.5
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - numba=0.61.2
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.5.4
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pint=0.25
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.5.0
  - pooch=1.8.2
  - poppler=24.09.0
  - poppler-data=0.4.12
  - proj=9.3.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.1
  - pure_eval=0.2.3
  - py-xgboost=3.0.1
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyogrio=0.10.0
  - pyparsing=3.2.5
  - pyproj=3.6.1
  - pyshp=3.0.2
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.3
  - rasterio=1.4.3
  - rasterstats=0.20.0
  - rav1e=0.7.1
  - re2=2024.07.02
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rioxarray=0.18.1
  - rpds-py=0.27.1
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shap=0.47.2
  - shapely=2.1.1
  - simplejson=3.19.2
  - six=1.17.0
  - slicer=0.0.8
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - tbb=2021.13.0
  - tblib=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tiledb=2.3.3
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.3.0
  - toolz=1.1.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xarray=2025.10.1
  - xerces-c=3.2.5
  - xgboost=3.0.1
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - adjusttext==1.3.0
      - cattrs==25.3.0
      - flatbuffers==25.9.23
      - hdbscan==0.8.41
      - jh2==5.0.10
      - niquests==3.15.2
      - numpy==2.3.4
      - openmeteo-requests==1.7.4
      - openmeteo-sdk==1.22.0
      - pynndescent==0.5.13
      - qh3==1.5.5
      - requests-cache==1.2.1
      - retry-requests==2.0.0
      - scikit-posthocs==0.11.4
      - umap-learn==0.5.9.post2
      - url-normalize==2.2.1
      - urllib3-future==2.14.906
      - wassima==2.0.2
prefix: C:\Users\dias3\miniconda3\envs\geoenv
